#!/usr/bin/env bash
# build-catalog.sh — locale/*.po → lib/catalog.sh (bash 3.2 case-нигезле эзләү).
# Тәрҗемәчеләр .po файлларын үзгәртә; бу скрипт каталогны яңадан җыя.
# Translators edit .po files; this regenerates the runtime catalog.
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")/.." && pwd)"
OUT="$HERE/lib/catalog.sh"

{
  echo "# shellcheck shell=bash"
  echo "# GENERATED by scripts/build-catalog.sh — DO NOT EDIT. Edit locale/*.po."
  echo "catalog_lookup() { # \$1=lang \$2=key"
  echo "  case \"\$1:\$2\" in"
  for po in "$HERE"/locale/*.po; do
    lang="$(basename "$po" .po)"
    awk -v lang="$lang" '
      function unq(s){ sub(/^msg[a-z]+ *"/,"",s); sub(/"$/,"",s);
                       gsub(/\\"/,"\"",s); gsub(/\\\\/,"\\",s); return s }
      function esc(s){ gsub(/'"'"'/,"'"'"'\\'"'"''"'"'",s); return s }  # '\''  →  '\''\'\'''\''
      BEGIN { q="'"'"'" }   # берле кавычка / single quote
      /^msgid "/  { key=unq($0); next }
      /^msgstr "/ { val=unq($0);
                    if (key!="" && val!="")
                      printf "    %s:%s) printf %s%%s%s %s%s%s ;;\n", \
                             lang, key, q, q, q, esc(val), q;
                    key=""; next }
    ' "$po"
  done
  echo "    *) printf '%s' \"\$2\" ;;"
  echo "  esac"
  echo "}"
} > "$OUT"

echo "◆ Каталог җыелды / catalog built: lib/catalog.sh ($(grep -c ') printf' "$OUT") юл)"
